// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeMtOLqMmPfhRUv_0VMuCzfpz_StbWWz0',
    appId: '1:666150422144:web:860bbc5f2b49fb956dc865',
    messagingSenderId: '666150422144',
    projectId: 'fruit-hub-40478',
    authDomain: 'fruit-hub-40478.firebaseapp.com',
    storageBucket: 'fruit-hub-40478.firebasestorage.app',
    measurementId: 'G-J3CXQ3DKBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArvpjZJuCntpDsGtDvKvjxbXe9wwRWxu8',
    appId: '1:666150422144:android:9247d35ec26c27906dc865',
    messagingSenderId: '666150422144',
    projectId: 'fruit-hub-40478',
    storageBucket: 'fruit-hub-40478.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxat2QiK93Y4Yjhs3visM0Aig65EPYbrk',
    appId: '1:666150422144:ios:f4a0f59b2802e8316dc865',
    messagingSenderId: '666150422144',
    projectId: 'fruit-hub-40478',
    storageBucket: 'fruit-hub-40478.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxat2QiK93Y4Yjhs3visM0Aig65EPYbrk',
    appId: '1:666150422144:ios:f4a0f59b2802e8316dc865',
    messagingSenderId: '666150422144',
    projectId: 'fruit-hub-40478',
    storageBucket: 'fruit-hub-40478.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeMtOLqMmPfhRUv_0VMuCzfpz_StbWWz0',
    appId: '1:666150422144:web:6671e827cdf1c33c6dc865',
    messagingSenderId: '666150422144',
    projectId: 'fruit-hub-40478',
    authDomain: 'fruit-hub-40478.firebaseapp.com',
    storageBucket: 'fruit-hub-40478.firebasestorage.app',
    measurementId: 'G-JP9S1127PB',
  );
}
